version: "3.8"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports: ["5432:5432"]
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.6
    ports: [
      "5775:5775/udp",
      "6831:6831/udp",
      "6832:6832/udp",
      "5778:5778",
      "16686:16686",
      "14268:14268",
      "9411:9411"
    ]
  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"
  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana
    network_mode: "host"